stages:
  - build

default:
  image:
    name: registry.gitlab.com/kicad/kicad-ci/source_containers/master/fedora:36
    entrypoint: ["/bin/sh", "-c"]

include:
  - local: '/.gitlab/Fedora-Linux-CI.yml'
